Перевод комментариев в разделе iOpt на английский для документации
aimclub/iOpt pull request #164
Opened 2023-10-09 05:05 UTC by ashtanyuk

2023-10-10 11:12 UTC, alvls requested changes

2023-10-10 11:12 UTC, alvls commented on iOpt/method/method.py
> +        Recalculation of features for all search intervals.
Заменить на 
Recalculate characteristics for all search intervals

2023-10-10 11:12 UTC, alvls commented on iOpt/method/method.py
> +        Compute the point of a new trial :math:`x^{k+1}` in a given interval :math:`[x_{t-1},x_t]`.
Убрать точку в конце

2023-10-10 11:12 UTC, alvls commented on iOpt/method/method.py
> +        Calculating the point of a new trial :math:`x^{k+1}`.
Заменить Calculating на Calculate, убрать точку в конце

2023-10-10 11:12 UTC, alvls commented on iOpt/method/method.py
> +        Performing a search trial at a given point.
Заменить Performing на Perform, убрать точку в конце

2023-10-10 11:12 UTC, alvls commented on iOpt/method/method.py
> +        Computing an estimate of the Gelder constant between curr_point and left_point.
Заменить Computing на Calculate, убрать точку в конце

2023-10-10 11:12 UTC, alvls commented on iOpt/method/method.py
> +        :param left_point: left interval point
Поставить точки в конце строк

2023-10-10 11:12 UTC, alvls commented on iOpt/method/method.py
> +        Calculating the global characteristic of an interval [left_point, curr_point].
Заменить Calculating на Calculate, убрать точку в конце

2023-10-10 11:12 UTC, alvls commented on iOpt/method/method.py
> +          a new point into the repository.
Заменить на 
Update all search information: interval lengths, Gölder constants, all characteristics and inserts
  a new point into the repository

2023-10-10 11:12 UTC, alvls commented on iOpt/method/method.py
> +        :param oldpoint: right point of the interval to which the new point belongs
Поставить точки в конце строк

2023-10-10 11:12 UTC, alvls commented on iOpt/method/method.py
> +        Updates the optimum estimate.
Заменить на 
Update the optimum estimate

2023-10-10 11:13 UTC, alvls commented
Антон, я выписал часть замечаний. Далее предлагаю исправить аналогично.

2023-10-18 09:40 UTC, ashtanyuk commented
Александр, замечания учел и исправил везде где смог)

2023-10-19 11:34 UTC, alvls requested changes

2023-10-19 11:34 UTC, alvls commented on iOpt/method/parallel_process.py
> +    The ParallelProcess class implements parallelisation at the level of threads (python processes)
Заменить parallelisation на parallelization

2023-10-19 11:34 UTC, alvls commented on iOpt/method/process.py
> +        :return: Current evaluation of the solution to the optimisation problem.
Здесь и далее заменить optimisation на optimization

2023-10-19 11:34 UTC, alvls commented on iOpt/method/search_data.py
>      The CharacteristicsQueue class is designed to store a prioritised queue of
Удалить of в конце строки

2023-10-19 11:34 UTC, alvls commented on iOpt/method/search_data.py
> +        Allow a pair of trial intervals to be added to the first iteration of the AGP.
Заменить AGP на GSA

2023-10-19 11:34 UTC, alvls commented on iOpt/method/search_data.py
> +        Clear the feature queue
Здесь и далее заменить feature на characteristic

2023-10-19 11:34 UTC, alvls commented on iOpt/output_system/listeners/animate_painters.py
>      The AnimationPaintListener class is an event listener. It contains handler methods that produce a dynamically updating image of the optimisation process in response to events.
Заменить AnimationPaintListener на AnimatePainterNDListener
Ниже в комментарии к методу __init__ исправить название класса

2023-10-19 11:34 UTC, alvls commented on iOpt/output_system/listeners/console_outputers.py
>      The ConsoleFullOutputListener class is an event listener. It contains handler methods that produce console output as a
Заменить ConsoleFullOutputListener на ConsoleOutputListener

2023-10-19 11:34 UTC, alvls commented on iOpt/output_system/listeners/static_painters.py
>      The StaticPaintListener class is an event listener. It contains a method handler that produces an image as a reaction to the method's completion.
Заменить StaticPaintListener на StaticPainterListener

2023-10-19 11:34 UTC, alvls commented on iOpt/output_system/listeners/static_painters.py
>      The StaticNDPaintListener class is an event listener. It contains a method handler that produces an image as a
Заменить StaticNDPaintListener на StaticPainterNDListener

2023-10-19 11:34 UTC, alvls commented on iOpt/solution.py
> +        :param best_trials: Solving the optimisation problem.
Заменить Solving на Solution of

2023-11-01 09:05 UTC, merged